/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'catalogos-agresores': RouteRecordInfo<'catalogos-agresores', '/catalogos/agresores', Record<never, never>, Record<never, never>>,
    'catalogos-areas': RouteRecordInfo<'catalogos-areas', '/catalogos/areas', Record<never, never>, Record<never, never>>,
    'catalogos-municipios': RouteRecordInfo<'catalogos-municipios', '/catalogos/municipios', Record<never, never>, Record<never, never>>,
    'catalogos-sitios-agresion': RouteRecordInfo<'catalogos-sitios-agresion', '/catalogos/sitios-agresion', Record<never, never>, Record<never, never>>,
    'catalogos-tipos-agresion': RouteRecordInfo<'catalogos-tipos-agresion', '/catalogos/tipos-agresion', Record<never, never>, Record<never, never>>,
    'catalogos-tipos-incidente': RouteRecordInfo<'catalogos-tipos-incidente', '/catalogos/tipos-incidente', Record<never, never>, Record<never, never>>,
    'catalogos-tipos-servicio': RouteRecordInfo<'catalogos-tipos-servicio', '/catalogos/tipos-servicio', Record<never, never>, Record<never, never>>,
    'catalogos-tipos-solicitante': RouteRecordInfo<'catalogos-tipos-solicitante', '/catalogos/tipos-solicitante', Record<never, never>, Record<never, never>>,
    'delegaciones': RouteRecordInfo<'delegaciones', '/delegaciones', Record<never, never>, Record<never, never>>,
    'denegado': RouteRecordInfo<'denegado', '/denegado', Record<never, never>, Record<never, never>>,
    'elementos': RouteRecordInfo<'elementos', '/elementos', Record<never, never>, Record<never, never>>,
    'estadisticas': RouteRecordInfo<'estadisticas', '/estadisticas', Record<never, never>, Record<never, never>>,
    'index copy': RouteRecordInfo<'index copy', '/index copy', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'logs': RouteRecordInfo<'logs', '/logs', Record<never, never>, Record<never, never>>,
    'reportes': RouteRecordInfo<'reportes', '/reportes', Record<never, never>, Record<never, never>>,
    'unidades': RouteRecordInfo<'unidades', '/unidades', Record<never, never>, Record<never, never>>,
    'usuarios': RouteRecordInfo<'usuarios', '/usuarios', Record<never, never>, Record<never, never>>,
  }
}
