/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'administrador-config-pages': RouteRecordInfo<'administrador-config-pages', '/administrador/config-pages', Record<never, never>, Record<never, never>>,
    'catalogos-areas': RouteRecordInfo<'catalogos-areas', '/catalogos/areas', Record<never, never>, Record<never, never>>,
    'catalogos-cargo': RouteRecordInfo<'catalogos-cargo', '/catalogos/cargo', Record<never, never>, Record<never, never>>,
    'catalogos-delegacion': RouteRecordInfo<'catalogos-delegacion', '/catalogos/delegacion', Record<never, never>, Record<never, never>>,
    'catalogos-dia': RouteRecordInfo<'catalogos-dia', '/catalogos/dia', Record<never, never>, Record<never, never>>,
    'catalogos-estado': RouteRecordInfo<'catalogos-estado', '/catalogos/estado', Record<never, never>, Record<never, never>>,
    'catalogos-estado-civil': RouteRecordInfo<'catalogos-estado-civil', '/catalogos/estado-civil', Record<never, never>, Record<never, never>>,
    'catalogos-grado-estudios': RouteRecordInfo<'catalogos-grado-estudios', '/catalogos/grado-estudios', Record<never, never>, Record<never, never>>,
    'catalogos-grupo-sanguineo': RouteRecordInfo<'catalogos-grupo-sanguineo', '/catalogos/grupo-sanguineo', Record<never, never>, Record<never, never>>,
    'catalogos-idioma': RouteRecordInfo<'catalogos-idioma', '/catalogos/idioma', Record<never, never>, Record<never, never>>,
    'catalogos-medio-difusion': RouteRecordInfo<'catalogos-medio-difusion', '/catalogos/medio-difusion', Record<never, never>, Record<never, never>>,
    'catalogos-nacionalidad': RouteRecordInfo<'catalogos-nacionalidad', '/catalogos/nacionalidad', Record<never, never>, Record<never, never>>,
    'catalogos-parentesco': RouteRecordInfo<'catalogos-parentesco', '/catalogos/parentesco', Record<never, never>, Record<never, never>>,
    'catalogos-tipo-contacto': RouteRecordInfo<'catalogos-tipo-contacto', '/catalogos/tipo-contacto', Record<never, never>, Record<never, never>>,
    'catalogos-tipo-documento': RouteRecordInfo<'catalogos-tipo-documento', '/catalogos/tipo-documento', Record<never, never>, Record<never, never>>,
    'catalogos-tipo-usuario': RouteRecordInfo<'catalogos-tipo-usuario', '/catalogos/tipo-usuario', Record<never, never>, Record<never, never>>,
    'catalogos-turno': RouteRecordInfo<'catalogos-turno', '/catalogos/turno', Record<never, never>, Record<never, never>>,
    'delegaciones': RouteRecordInfo<'delegaciones', '/delegaciones', Record<never, never>, Record<never, never>>,
    'denegado': RouteRecordInfo<'denegado', '/denegado', Record<never, never>, Record<never, never>>,
    'elementos': RouteRecordInfo<'elementos', '/elementos', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'logs': RouteRecordInfo<'logs', '/logs', Record<never, never>, Record<never, never>>,
    'usuarios': RouteRecordInfo<'usuarios', '/usuarios', Record<never, never>, Record<never, never>>,
    'voluntarios': RouteRecordInfo<'voluntarios', '/voluntarios', Record<never, never>, Record<never, never>>,
  }
}
