/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'administrador-config-pages': RouteRecordInfo<'administrador-config-pages', '/administrador/config-pages', Record<never, never>, Record<never, never>>,
    'catalogos-tipo-usuario': RouteRecordInfo<'catalogos-tipo-usuario', '/catalogos/tipo-usuario', Record<never, never>, Record<never, never>>,
    'delegaciones': RouteRecordInfo<'delegaciones', '/delegaciones', Record<never, never>, Record<never, never>>,
    'denegado': RouteRecordInfo<'denegado', '/denegado', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'logs': RouteRecordInfo<'logs', '/logs', Record<never, never>, Record<never, never>>,
    'usuarios': RouteRecordInfo<'usuarios', '/usuarios', Record<never, never>, Record<never, never>>,
  }
}
